[package]
name = "chyron-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "chyron"
crate-type = ["staticlib", "lib"]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cbindgen = "0.20.0"
